# Generated by Django 5.2.12 on 2026-03-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="display",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="technology",
            name="display",
            field=models.BooleanField(default=False),
        ),
    ]
