# Generated by Django 5.2.12 on 2026-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_skill_order_index_technology_order_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="authors",
            field=models.TextField(blank=True, default="A. Mechache & H. Kheddouci"),
        ),
    ]
